### PR TITLE
Add back the documentation on Actions

### PR DESCRIPTION
**Pull request by jdillard**
I saw these linked in https://github.com/errata-ai/vale-vscode/issues/109

## Summary of changes

- Add back the documentation on Actions
- Remove the mention of Atom, since it has been [sunset](https://github.blog/2022-06-08-sunsetting-atom/).

## Preview

- [Actions](https://deploy-preview-29--eclectic-semifreddo-be083c.netlify.app/docs/topics/styles/#actions)

### CODE REVIEW

**Comment by jdkato** [comment]
This is being re-implemented by @ChrisChinchilla, so I'll wait until we can confirm that the old docs are accurate.

**Comment by jdillard** [comment]
Ah, my bad! I thought it was just sitting there waiting to be implemented. Part of the reason I decided to work on this was to get more familiar with actions, and in doing so hopefully confirm the accuracy.

**Comment by ChrisChinchilla** [comment]
Yeah, it was merged here - https://github.com/errata-ai/vale.sh/pull/24

But there's a bit more to do to "standardise" things, when I am finished with figuring out how to get to spell checking supported in VSCode will have more to add and will probably pick some of your suggestions here, so let's leave the PR parked here for now.

**Comment by jdkato** [comment]
The docs have been updated.

**Pull request closed without merging**
