### PR TITLE
Document `CommentDelimiters` configuration option

### PR DESCRIPTION
**Pull request by fviolette**
Featured in [3.8.0](https://github.com/errata-ai/vale/releases/tag/v3.8.0).
Original code contribution is https://github.com/errata-ai/vale/pull/900

### CODE REVIEW

**Comment by jdkato** [comment]
Thanks for working on this.

The intended use case for this is to *replace* the use of HTML syntax, so an example would look something like this:

```ini
[formats]
mdx = md

[*.mdx]
BasedOnStyles = Vale

CommentDelimiters = {/*, */}
```

and then it would be used like so:

```mdx
{/* vale off */}

This is some text ACT test

This is some text ACT test

{/* vale on */}

{/* vale vale.Redundancy = NO */}

This is some text ACT test

{/* vale vale.Redundancy = YES */}
```

See [testdata/fixtures/comments](https://github.com/errata-ai/vale/tree/v3/testdata/fixtures/comments) for a complete example.

**Comment by fviolette** [comment]
Glad to hear this is how it should work (without the double HTML and the custom comment delimiters).

This is not working for me at the moment. I'm on macOS and using Vale 3.8.0.
The example I added was the only way to get it working (as a passthrough) but I'll update it as per your suggestion

```
[formats]
mdx = md

[*.mdx] 
BasedOnStyles = Vale

CommentDelimiters = {/*, */}
```

^ FWIW, [*.mdx] or [*.md] above produce the same.

```
{/* vale off */}

vale spelling

{/* vale on */}

{/* vale vale.Spelling = NO */}

azeqsd

{/* vale vale.Spelling = YES */}

azeqsd
```

Both 'azeqsd' occurrences are firing for me.

Is there anything I'm doing wrong?

**Comment by fviolette** [comment]
Glad to hear this is how it should work (without the double HTML and the custom comment delimiters).

This is not working for me at the moment. I'm on macOS and using Vale 3.8.0.
The example I added was the only way to get it working (as a passthrough) but I'll update it as per your suggestion

```
[formats]
mdx = md

[*.mdx] 
BasedOnStyles = Vale

CommentDelimiters = {/*, */}
```

^ FWIW, [*.mdx] or [*.md] above produce the same.

```
{/* vale off */}

vale spelling

{/* vale on */}

{/* vale vale.Spelling = NO */}

azeqsd

{/* vale vale.Spelling = YES */}

azeqsd
```

Both 'azeqsd' occurrences are firing for me.

Is there anything I'm doing wrong?

**Comment by fviolette** [comment]
I got the `testdata` to work so it is on my side. I'll update the document after I fix this.
Thanks for leading me into the right direction 👍

**Comment by fviolette** [comment]
Example updated.

**Pull request merged**
